# Generated by Django 5.2 on 2026-09-22 09:38

import apps.accounts.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Society",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                ("invite_code", models.CharField(blank=True, max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "societies",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("code_hash", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["phone", "expires_at"], name="accounts_ot_phone_c0d092_idx"
                    ),
                    models.Index(fields=["consumed_at"], name="accounts_ot_consume_03ebf7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(db_index=True, max_length=150, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("main_admin", "Main Admin"),
                            ("society_admin", "Society Admin"),
                            ("resident", "Resident"),
                            ("vendor", "Vendor"),
                        ],
                        default="resident",
                        max_length=30,
                    ),
                ),
                ("flat_no", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user can access the Django admin site.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "society_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="society_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="accounts.society",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="society",
            name="admin_user_id",
            field=models.ForeignKey(
                blank=True,
                db_column="admin_user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administered_societies",
                to="accounts.user",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["society_id", "role"], name="accounts_us_society_65e6e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"),
        ),
        migrations.AddIndex(
            model_name="society",
            index=models.Index(fields=["city"], name="accounts_so_city_c3d610_idx"),
        ),
        migrations.AddIndex(
            model_name="society",
            index=models.Index(fields=["is_active"], name="accounts_so_is_acti_996578_idx"),
        ),
    ]
